title: 門前の小僧、他派の経を読む
description: >-
  本来は、門前の小僧、習わぬ経を読む。
  日頃から見聞きしているものは、意識しなくても自然と知識や技術が身につく、という意味。
  他派の経をわざわざ読むのは、日頃から見聞きしているものに対して客観的になるため
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nightusk.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
